---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/7 16:50
---
---
---
--[[local base = require("kong.plugins.base_plugin")
local CustomHandler = BasePlugin:extend()
function CustomHandler:new()
    CustomHandler.super.new(self, "my-custom-plugin")
end]]
--pcall(function(i) print(i) error('error..') end, 33)
max = function(a,b)
    if  a>b  then
        return a
    else
        return b
    end
end
function test(a,b)
    do
        if true then
            max(a,b)
            error('参数类型错误',1)
        end

    end
end
print(test(10,c))